### ISSUE TITLE
Error message "Error in checkvec(posabunds, possizes) :    Gates sizes must be in numeric vectors matching abundance table columns."

### ISSUE THREAD

**Issue by katharineseton** [microbialman/IgAScores#1]
when I tried to run the iga scores function:

` IgG_probability <- igascores(posabunds = IgG_pos, possizes = possize, presortabunds = sybr_all, method="prob")`

I get the error message:

```
Error in checkvec(posabunds, possizes) : 
  Gates sizes must be in numeric vectors matching abundance table columns.
```

What does this mean?

**Comment by microbialman** [comment]
The checkvec is checking that the vector of fraction sizes (possize in this case) is a numeric vector and is of the same dimensions at the abundance tables. possizes should have the same number of values as the number of samples in the abundance tables. The abundance tables will also need to be in the correct orientation (samples as columns and taxa as rows).

If this is the case and you are still getting errors, if you are happy to provide a reproducible example I will investigate further, thanks.

**Comment by katharineseton** [comment]
The issue has been resolved, thank you for your help.
